name: barista_pro
description: Cross-platform app for audits & attestation with local storage and PDF reports.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter: { sdk: flutter }
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  go_router: ^14.2.1
  intl: ^0.19.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  uuid: ^4.5.1
  collection: ^1.18.0
  pdf: ^3.10.8
  printing: ^5.13.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/placeholder_bg.png
    - assets/images/placeholder_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/placeholder_icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/placeholder_icon.png
  android: true
  ios: true
  android_12:
    image: assets/images/placeholder_icon.png
